apiVersion: v1
kind: Secret
metadata:
  name: xdp-firewall-db
  namespace: xdp-firewall
type: Opaque
stringData:
  database_url: postgres://xdp_firewall:xdp_firewall@postgres.middleware.svc.cluster.local:5432/xdp_firewall
  api_token: change-this-token
